name: Build Tauri App (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. リポジトリのチェックアウト
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Rust ツールチェインのセットアップ
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # 3. LLVM ツールの追加
      - name: Add llvm-tools-preview
        run: rustup component add llvm-tools-preview

      # 4. Node.js のセットアップ
      # Tauri ビルドに必要な場合のみ（Node.js が不要ならこのステップを削除可能）
      # - name: Set up Node.js
        # uses: actions/setup-node@v3
        # with:
        #   node-version: '16'

      # 5. Tauri ビルド用の依存関係をインストール（Node.js 依存が必要な場合）
      # - name: Install Node.js dependencies
      #   run: |
      #     cd src-tauri
      #     npm install

      # 6. Tauri アプリのビルド（cargo でのビルド）
      - name: Build Tauri App with Cargo
        run: |
          cargo build --release

      # 7. バンドルの作成
      - name: Bundle the Tauri App
        run: |
          cargo tauri build

      # 8. アーティファクトの保存
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TauriApp-Windows
          path: src-tauri/target/release/bundle/
